name: bullfly666 # 名称随意
on: 
  schedule: 
  - cron: '*/40 * * * *'
  workflow_dispatch: 
  watch: 
   types: started 
  repository_dispatch:
    types: bullfly666
jobs: 
 repo-sync: 
     env: 
       PAT: ${{ secrets.PAT }} 
     runs-on: ubuntu-latest 
     if: github.event.repository.owner.id == github.event.sender.id 
     steps: 
      - uses: actions/checkout@v2 
        with: 
          persist-credentials: false 
    
      - name: sync bullfly666
        uses: repo-sync/github-sync@v2 
        if: env.PAT 
        with: 
          source_repo: "https://github.com/bullfly666/percollect.git" # 上游仓库地址
          source_branch: "main" 
          destination_branch: "bullfly666" # 按照自己仓库分支名称修改
          github_token: ${{ secrets.PAT }} 